#!/bin/sh

echo "Removing previous workers"
rm -rf {{pkg.svc_var_path}}/workers

echo "Copying workers"
mkdir -p {{pkg.svc_var_path}}/workers
cp -a {{pkg.path}}/workers {{pkg.svc_var_path}}
chown -R {{pkg.svc_user}}:{{pkg.svc_group}} {{pkg.svc_var_path}}/workers

echo "Conveyor expects to write its own config. Copying instead of linking."
echo "Any changes made will get reset on next init."
echo "Copying {{pkg.svc_config_path}}/conveyor.yml to {{pkg.svc_var_path}}/.conveyor"
cp -f {{pkg.svc_config_path}}/conveyor.yml {{pkg.svc_var_path}}/.conveyor
chown {{pkg.svc_user}}:{{pkg.svc_group}} {{pkg.svc_var_path}}/.conveyor