# Use this file to templatize your application's native configuration files.
# See the docs at https://www.habitat.sh/docs/create-packages-configure/.

threadpool = 5
timeout = 600

landfall_raw_path = "/home/processing/raw"
landfall_shared_path = "/gluster/cache"
sandy_controller = "http://nrt-ops.gina.alaska.edu"
