name: Build
on: workflow_dispatch
jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: redhat/ubi8
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: install prerecs
              run: |
                 dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
                 dnf -y update && dnf -y install openssh-clients wget bzip2 tar make xz lbzip2 
            - name: Add SSH key
              env:
                  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
              run: |
                  mkdir -p /home/runner/.ssh
                  echo "${{ secrets.DEPLOY_KEY }}" > /home/runner/.ssh/github_actions
                  chmod 600 /home/runner/.ssh/github_actions
                  ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
                  ssh-add /home/runner/.ssh/github_actions
                  ssh-add -L
                  pwd
            - name: Install Conda
              env:
                  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
              run: |
                  mkdir -p $HOME/anaconda
                  wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/anaconda/miniconda.sh
                  bash ~/anaconda/miniconda.sh -b -u -p ~/anaconda
                  ~/anaconda/bin/conda init bash
            - name: Build
              env:
                  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
              run: |
                  mkdir -p /opt/gina
                  bash -l ./build.bash
            - name: publish
              env:
                  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
              run: |
                  sha256sum *.bz2 *.xz
                  scp -i /home/runner/.ssh/github_actions -J jecable@gateway.gina.alaska.edu *.bz2 *.xz ginauser@bigdipper.alaska.edu:/home/ginauser/bs4/gina-packages/nrt 
                  
                
